a=int(input("Enter the number1::"))
b=int(input("Enter the number2::"))
print("Addition::")
add=(a+b)
print(add)
print("Subtraction::")
sub=(a-b)
print(sub)
print("multiplication::")
mul=(a*b)
print(mul)
print("Division::")
div=(a/b)
print(div)
